#include "card.h"
#include "cardlibrary.h"
#include <QImage>

const std::vector<Card> CardLibrary::cards = {
    // 13 Spades cards
    {Card(QString("Ace of Spades"), Suit::Spade, CardValue(14), QImage("card_images/ace_of_spades.png"))},
    {Card(QString("2 of Spades"), Suit::Spade, CardValue(2), QImage("card_images/2_of_spades.png"))},
    {Card(QString("3 of Spades"), Suit::Spade, CardValue(3), QImage("card_images/3_of_spades.png"))},
    {Card(QString("4 of Spades"), Suit::Spade, CardValue(4), QImage("card_images/4_of_spades.png"))},
    {Card(QString("5 of Spades"), Suit::Spade, CardValue(5), QImage("card_images/5_of_spades.png"))},
    {Card(QString("6 of Spades"), Suit::Spade, CardValue(6), QImage("card_images/6_of_spades.png"))},
    {Card(QString("7 of Spades"), Suit::Spade, CardValue(7), QImage("card_images/7_of_spades.png"))},
    {Card(QString("8 of Spades"), Suit::Spade, CardValue(8), QImage("card_images/8_of_spades.png"))},
    {Card(QString("9 of Spades"), Suit::Spade, CardValue(3), QImage("card_images/9_of_spades.png"))},
    {Card(QString("10 of Spades"), Suit::Spade, CardValue(10), QImage("card_images/10_of_spades.png"))},
    {Card(QString("Jack of Spades"), Suit::Spade, CardValue(11), QImage("card_images/jack_of_spades.png"))},
    {Card(QString("Queen of Spades"), Suit::Spade, CardValue(12), QImage("card_images/queen_of_spades.png"))},
    {Card(QString("King of Spades"), Suit::Spade, CardValue(13), QImage("card_images/king_of_spades.png"))},
    // 13 Clubs cards
    {Card(QString("Ace of Clubs"), Suit::Club, CardValue(14), QImage("card_images/ace_of_clubs.png"))},
    {Card(QString("2 of Clubs"), Suit::Club, CardValue(2), QImage("card_images/2_of_clubs.png"))},
    {Card(QString("3 of Clubs"), Suit::Club, CardValue(3), QImage("card_images/3_of_clubs.png"))},
    {Card(QString("4 of Clubs"), Suit::Club, CardValue(4), QImage("card_images/4_of_clubs.png"))},
    {Card(QString("5 of Clubs"), Suit::Club, CardValue(5), QImage("card_images/5_of_clubs.png"))},
    {Card(QString("6 of Clubs"), Suit::Club, CardValue(6), QImage("card_images/6_of_clubs.png"))},
    {Card(QString("7 of Clubs"), Suit::Club, CardValue(7), QImage("card_images/7_of_clubs.png"))},
    {Card(QString("8 of Clubs"), Suit::Club, CardValue(8), QImage("card_images/8_of_clubs.png"))},
    {Card(QString("9 of Clubs"), Suit::Club, CardValue(3), QImage("card_images/9_of_clubs.png"))},
    {Card(QString("10 of Clubs"), Suit::Club, CardValue(10), QImage("card_images/10_of_clubs.png"))},
    {Card(QString("Jack of Clubs"), Suit::Club, CardValue(11), QImage("card_images/jack_of_clubs.png"))},
    {Card(QString("Queen of Clubs"), Suit::Club, CardValue(12), QImage("card_images/queen_of_clubs.png"))},
    {Card(QString("King of Clubs"), Suit::Club, CardValue(13), QImage("card_images/king_of_clubs.png"))},
    // 13 Hearts cards
    {Card(QString("Ace of Hearts"), Suit::Heart, CardValue(14), QImage("card_images/ace_of_hearts.png"))},
    {Card(QString("2 of Hearts"), Suit::Heart, CardValue(2), QImage("card_images/2_of_hearts.png"))},
    {Card(QString("3 of Hearts"), Suit::Heart, CardValue(3), QImage("card_images/3_of_hearts.png"))},
    {Card(QString("4 of Hearts"), Suit::Heart, CardValue(4), QImage("card_images/4_of_hearts.png"))},
    {Card(QString("5 of Hearts"), Suit::Heart, CardValue(5), QImage("card_images/5_of_hearts.png"))},
    {Card(QString("6 of Hearts"), Suit::Heart, CardValue(6), QImage("card_images/6_of_hearts.png"))},
    {Card(QString("7 of Hearts"), Suit::Heart, CardValue(7), QImage("card_images/7_of_hearts.png"))},
    {Card(QString("8 of Hearts"), Suit::Heart, CardValue(8), QImage("card_images/8_of_hearts.png"))},
    {Card(QString("9 of Hearts"), Suit::Heart, CardValue(3), QImage("card_images/9_of_hearts.png"))},
    {Card(QString("10 of Hearts"), Suit::Heart, CardValue(10), QImage("card_images/10_of_hearts.png"))},
    {Card(QString("Jack of Hearts"), Suit::Heart, CardValue(11), QImage("card_images/jack_of_hearts.png"))},
    {Card(QString("Queen of Hearts"), Suit::Heart, CardValue(12), QImage("card_images/queen_of_hearts.png"))},
    {Card(QString("King of Hearts"), Suit::Heart, CardValue(13), QImage("card_images/king_of_hearts.png"))},
    // 13 Diamonds cards
    {Card(QString("Ace of Diamonds"), Suit::Diamond, CardValue(14), QImage("card_images/ace_of_diamonds.png"))},
    {Card(QString("2 of Diamonds"), Suit::Diamond, CardValue(2), QImage("card_images/2_of_diamonds.png"))},
    {Card(QString("3 of Diamonds"), Suit::Diamond, CardValue(3), QImage("card_images/3_of_diamonds.png"))},
    {Card(QString("4 of Diamonds"), Suit::Diamond, CardValue(4), QImage("card_images/4_of_diamonds.png"))},
    {Card(QString("5 of Diamonds"), Suit::Diamond, CardValue(5), QImage("card_images/5_of_diamonds.png"))},
    {Card(QString("6 of Diamonds"), Suit::Diamond, CardValue(6), QImage("card_images/6_of_diamonds.png"))},
    {Card(QString("7 of Diamonds"), Suit::Diamond, CardValue(7), QImage("card_images/7_of_diamonds.png"))},
    {Card(QString("8 of Diamonds"), Suit::Diamond, CardValue(8), QImage("card_images/8_of_diamonds.png"))},
    {Card(QString("9 of Diamonds"), Suit::Diamond, CardValue(3), QImage("card_images/9_of_diamonds.png"))},
    {Card(QString("10 of Diamonds"), Suit::Diamond, CardValue(10), QImage("card_images/10_of_diamonds.png"))},
    {Card(QString("Jack of Diamonds"), Suit::Diamond, CardValue(11), QImage("card_images/jack_of_diamonds.png"))},
    {Card(QString("Queen of Diamonds"), Suit::Diamond, CardValue(12), QImage("card_images/queen_of_diamonds.png"))},
    {Card(QString("King of Diamonds"), Suit::Diamond, CardValue(13), QImage("card_images/king_of_diamonds.png"))}
};
